-- ==============================================================================
-- SKRIP MIGRASI SUPABASE LENGKAP UNTUK PINTUKARIER.ID
-- Jalankan skrip ini di SQL Editor dashboard Supabase Anda
-- (https://supabase.com/dashboard/project/_/sql)
-- ==============================================================================

-- 1. Buat Tabel Lowongan Kerja (jobs)
CREATE TABLE IF NOT EXISTS public.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  location TEXT NOT NULL DEFAULT 'Remote',
  salary TEXT,
  type TEXT DEFAULT 'Full Time',
  desc TEXT,
  category TEXT DEFAULT 'IT & Software',
  status TEXT DEFAULT 'Menunggu Persetujuan',
  applyType TEXT DEFAULT 'whatsapp',
  applyTarget TEXT,
  requirements JSONB DEFAULT '[]'::jsonb,
  featured BOOLEAN DEFAULT false,
  applicantsCount INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Buat Tabel Pesanan CV Klien (cv_orders)
CREATE TABLE IF NOT EXISTS public.cv_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  package TEXT NOT NULL,
  status TEXT DEFAULT 'Menunggu Review',
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Berikan Hak Akses (Grants) ke role anon dan authenticated
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.jobs TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.cv_orders TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 4. Aktifkan Row Level Security (RLS)
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cv_orders ENABLE ROW LEVEL SECURITY;

-- 5. Buat Kebijakan RLS (Policies) untuk Tabel jobs
DROP POLICY IF EXISTS "Allow select jobs" ON public.jobs;
CREATE POLICY "Allow select jobs" ON public.jobs
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert jobs" ON public.jobs;
CREATE POLICY "Allow insert jobs" ON public.jobs
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update jobs" ON public.jobs;
CREATE POLICY "Allow update jobs" ON public.jobs
  FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow delete jobs" ON public.jobs;
CREATE POLICY "Allow delete jobs" ON public.jobs
  FOR DELETE USING (true);

-- 6. Buat Kebijakan RLS (Policies) untuk Tabel cv_orders
DROP POLICY IF EXISTS "Allow select cv_orders" ON public.cv_orders;
CREATE POLICY "Allow select cv_orders" ON public.cv_orders
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert cv_orders" ON public.cv_orders;
CREATE POLICY "Allow insert cv_orders" ON public.cv_orders
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update cv_orders" ON public.cv_orders;
CREATE POLICY "Allow update cv_orders" ON public.cv_orders
  FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow delete cv_orders" ON public.cv_orders;
CREATE POLICY "Allow delete cv_orders" ON public.cv_orders
  FOR DELETE USING (true);

-- 7. Data Awal Contoh untuk cv_orders (Optional)
INSERT INTO public.cv_orders (name, whatsapp, package, status, date)
VALUES
  ('Budi Santoso', '08123456789', 'Paket ATS Professional (Rp 99k)', 'Menunggu Review', CURRENT_DATE),
  ('Siti Rahma', '08987654321', 'Paket Bundle CV + LinkedIn (Rp 149k)', 'Selesai', CURRENT_DATE - INTERVAL '1 day')
ON CONFLICT DO NOTHING;

-- 8. Buat Tabel Statistik Kunjungan Website (site_stats)
CREATE TABLE IF NOT EXISTS public.site_stats (
  id BIGINT PRIMARY KEY DEFAULT 1,
  total_views BIGINT DEFAULT 1,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Hak Akses untuk site_stats
GRANT ALL ON TABLE public.site_stats TO anon, authenticated, service_role;
ALTER TABLE public.site_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow select site_stats" ON public.site_stats;
CREATE POLICY "Allow select site_stats" ON public.site_stats
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert site_stats" ON public.site_stats;
CREATE POLICY "Allow insert site_stats" ON public.site_stats
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update site_stats" ON public.site_stats;
CREATE POLICY "Allow update site_stats" ON public.site_stats
  FOR UPDATE USING (true) WITH CHECK (true);

-- Inisialisasi baris pertama jika belum ada
INSERT INTO public.site_stats (id, total_views, updated_at)
VALUES (1, 1250, NOW())
ON CONFLICT (id) DO NOTHING;

-- Function RPC untuk increment views secara aman & atomik
CREATE OR REPLACE FUNCTION increment_site_views()
RETURNS BIGINT AS $$
DECLARE
  new_views BIGINT;
BEGIN
  INSERT INTO public.site_stats (id, total_views, updated_at)
  VALUES (1, 1, NOW())
  ON CONFLICT (id)
  DO UPDATE SET total_views = public.site_stats.total_views + 1, updated_at = NOW()
  RETURNING total_views INTO new_views;
  
  RETURN new_views;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION increment_site_views() TO anon, authenticated, service_role;
